# Generated by Django 5.1.6 on 2026-05-24 16:16

import django.db.models.deletion
import portal_content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('app_description', models.TextField(default='This portal provides a centralized space for viewing information security documents, managing policy-related content, and accessing department updates based on assigned user permissions.')),
                ('mission', models.TextField(default='To protect organizational information assets by promoting secure, reliable, and responsible use of technology across all departments.')),
                ('vision', models.TextField(default='To build a security-conscious organization where information protection is embedded in every system, process, and decision.')),
                ('core_values', models.JSONField(default=portal_content.models.default_core_values)),
                ('pinned_notice_category', models.CharField(default='Security Notice', max_length=100)),
                ('pinned_notice_title', models.CharField(default='Quarterly Security Awareness Campaign', max_length=255)),
                ('pinned_notice_message', models.TextField(default='The InfoSec Department will conduct a quarterly security awareness campaign covering phishing prevention, data handling, and safe access practices.')),
                ('pinned_notice_author', models.CharField(blank=True, default='InfoSec Department', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_content_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_content',
            },
        ),
    ]
