# Generated by Django 5.1.6 on 2026-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notifications_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=255)),
                ('to_user_id', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('notifications_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
