# Generated by Django 5.1.6 on 2026-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='misc_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
