# Generated by Django 5.1.6 on 2026-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
