# Generated by Django 5.1.6 on 2026-03-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='authored_by',
        ),
    ]
