# Generated by Django 5.1.6 on 2026-04-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_lastupdated'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='authoredBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to='login.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_documents', to='login.user'),
        ),
    ]
