# Generated by Django 5.1.6 on 2026-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_authored_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to='documents/pdfs/'),
        ),
    ]
