# Generated by Django 5.1.6 on 2026-03-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='last_updated',
            new_name='lastReviewed',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='reviewed_by',
            new_name='reviewedBy',
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
