# Generated by Django 5.1.6 on 2026-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_last_updated_document_lastreviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='reviewedBy',
        ),
    ]
