# Generated by Django 5.1.6 on 2026-05-24 11:46

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_authoredby_alter_document_reviewedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to=documents.models.Document.document_pdf_path),
        ),
    ]
