# Generated by Django 5.1.6 on 2026-03-29 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_reviewedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
