# Generated by Django 5.1.6 on 2026-02-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS public.roles_permission (
                            role_id VARCHAR(255) PRIMARY KEY,
                            role_name VARCHAR(255) NOT NULL,
                            description TEXT NULL,
                            permissions TEXT NULL,
                            access_level INT NOT NULL DEFAULT 0
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS public.roles_permission CASCADE",
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS public.users (
                            user_id VARCHAR(255) PRIMARY KEY,
                            employee_id VARCHAR(255) NULL,
                            first_name VARCHAR(255) NOT NULL,
                            last_name VARCHAR(255) NOT NULL,
                            email VARCHAR(255) NOT NULL UNIQUE,
                            password VARCHAR(255) NOT NULL,
                            status VARCHAR(10) NOT NULL DEFAULT 'Active',
                            type VARCHAR(10) NOT NULL DEFAULT 'Employee',
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                            role_id VARCHAR(255) NULL REFERENCES public.roles_permission(role_id) ON DELETE CASCADE
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS public.users CASCADE",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='RolesPermission',
                    fields=[
                        ('role_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                        ('role_name', models.CharField(max_length=255)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('permissions', models.TextField(blank=True, null=True)),
                        ('access_level', models.IntegerField(choices=[(3, 'Read-Only'), (10, 'Full Access')], default=10)),
                    ],
                    options={
                        'db_table': 'roles_permission',
                    },
                ),
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                        ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('first_name', models.CharField(max_length=255)),
                        ('last_name', models.CharField(max_length=255)),
                        ('email', models.EmailField(max_length=255, unique=True)),
                        ('password', models.CharField(max_length=255)),
                        ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                        ('type', models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=10)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.rolespermission')),
                    ],
                    options={
                        'db_table': 'users',
                    },
                ),
            ],
        ),
    ]
