# Generated by Django 5.1.6 on 2026-02-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolesPermission',
            fields=[
                ('role_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('access_level', models.CharField(choices=[('Read-Only', 'Read Only'), ('Full Access', 'Full Access')], default='Full Access', max_length=20)),
            ],
            options={
                'db_table': 'roles_permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('type', models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.rolespermission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
