# Generated by Django 5.1.6 on 2026-05-23

import uuid

from django.db import migrations, models
import django.db.models.deletion


def seed_roles(apps, schema_editor):
    Role = apps.get_model('login', 'Role')
    User = apps.get_model('login', 'User')

    staff_role, _ = Role.objects.get_or_create(
        role_name='Staff',
        defaults={'modules': 'Home, Documents, Policies, RecentNews, Others'},
    )
    admin_role, _ = Role.objects.get_or_create(
        role_name='Admin',
        defaults={'modules': 'All'},
    )

    for user in User.objects.all():
        if getattr(user, 'role_id', None):
            continue

        user.role = admin_role if getattr(user, 'is_superuser', False) else staff_role
        user.save(update_fields=['role'])


def reverse_seed_roles(apps, schema_editor):
    User = apps.get_model('login', 'User')
    Role = apps.get_model('login', 'Role')

    User.objects.update(role=None)
    Role.objects.filter(role_name__in=['Admin', 'Staff']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('modules', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='login.role'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_role_id_fkey",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE public.users ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(role_id) ON DELETE SET NULL",
            reverse_sql="ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_role_id_fkey",
        ),
        migrations.RunPython(seed_roles, reverse_seed_roles),
    ]
