# Generated by Django 5.1.6 on 2026-05-23

from django.db import migrations, models
import uuid


def populate_usernames(apps, schema_editor):
    User = apps.get_model('login', 'User')
    for user in User.objects.all():
        if getattr(user, 'username', None):
            continue
        user.username = user.email or str(user.user_id)
        user.save(update_fields=['username'])


def reverse_populate_usernames(apps, schema_editor):
    User = apps.get_model('login', 'User')
    User.objects.update(username='')


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_role_and_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_usernames, reverse_populate_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
