# Generated by Copilot on 2026-05-24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_auth_user_like_shape'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_column='user_id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]